<?php

/**
 * @file
 * Provide a field to store and display crowdfunding links and widgets.
 */

/**
 * Implements hook_theme().
 */
function funding_theme($existing, $type, $theme, $path) {
  return [
    'funding_link' => [
      'variables' => [
        'provider' => NULL,
        'url' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_hook().
 */
function template_preprocess_funding_link(&$variables) {
  $variables['attributes'] = [
    'href' => $variables['url'],
  ];
}
