# Schema for the configuration files of the Funding module.
funding.settings:
  type: config_object
  label: 'Funding settings'
  mapping:
    providers_configurations:
      type: sequence
      label: 'Providers Configurations'
